title: "Forestbrook.net Knowledge Base"
remote_theme: pmarsceill/just-the-docs
search_enabled: true
search_tokenizer_separator: /[\s/]+/
color_scheme: "light"
logo: "/assets/images/fblogo.png"
footer_content: "Copyright &copy; 2020 Marcel Wolterbeek, Amsterdam, The Netherlands.<br/>Source code and documentation licensed by a <a href=\"https://github.com/Forestbrook/Forestbrook.github.io/blob/master/LICENSE.txt\">MIT license.</a>"
