title: "Forestbrook.net Knowledge Base"
remote_theme: pmarsceill/just-the-docs
search_enabled: false
color_scheme: "light"
logo: "/assets/images/fblogo.png"
footer_content: "Copyright &copy; 2020 Marcel Wolterbeek, Amsterdam, The Netherlands.<br/>Distributed by an <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"